{% set name = "btrees" %}
{% set version = "4.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/BTrees-{{ version }}.tar.gz
  sha256: 005c03b48029d67a288e7608798c37ac249f2c069b6f5183640a9499dcd8faa3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - persistent
    - pip
    - python
  run:
    - persistent >=4.1.0
    - python
    - zope.interface >=5.0.0

test:
  imports:
    - BTrees
    - BTrees.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/BTrees
  summary: Scalable persistent object containers
  doc_url: https://pythonhosted.org/BTrees/
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
