schema_version: 1

context:
  version: "6.5"

package:
  name: btrees
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/btrees/btrees-${{ version }}.tar.gz
  sha256: 1876cad0ebcac3f68dadcdca8018ea6cb76b334f9991a73aa85cbb0cb8fd8cf0

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools
    - persistent
    - pip
  run:
    - python
    - persistent >=4.1.0
    - zope.interface >=5.0.0

tests:
  - python:
      imports:
        - BTrees
        - BTrees.tests
      pip_check: true
  - requirements:
      run:
        - persistent >=4.4.3
        - transaction
        - zodb
    script:
      - python -m unittest discover -b -v BTrees.tests

about:
  summary: Scalable persistent object containers
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  homepage: https://github.com/zopefoundation/BTrees
  documentation: https://btrees.readthedocs.io

extra:
  recipe-maintainers:
    - osamples
    - izahn
    - mgorny
